# Core & Execution
port=0
user=nbxyz
keep-in-foreground
dhcp-no-override

# TFTP Settings
enable-tftp
tftp-secure
tftp-root=/config/menus

# Logging
log-facility=-
log-dhcp
log-queries

# Vendor & PXE Options
# DHCP_PXE_DISCOVERY_CONTROL: Disable multicast/broadcast discovery
dhcp-option=vendor:PXEClient,6,2b

# Detection: Is this a native iPXE request or a BIOS/EFI ROM request?
dhcp-match=set:ipxe-bios,175,33
dhcp-match=set:ipxe-efi,175,36
# Tag for "not iPXE" to handle the initial ROM boot
tag-if=set:!ipxe-ok,tag:!ipxe-bios,tag:!ipxe-efi

# Initial Boot: Provide files for standard PXE ROMs
pxe-service=tag:!ipxe-ok,X86PC,PXE,netboot.xyz-undionly.kpxe
pxe-service=tag:!ipxe-ok,BC_EFI,PXE,netboot.xyz.efi
pxe-service=tag:!ipxe-ok,X86-64_EFI,PXE,netboot.xyz.efi

# Force the PXE identifier in the response even if not strictly requested
dhcp-option-force=tag:ipxe-efi,option:vendor-class,PXEClient

conf-dir=/etc/dnsmasq.d/,*.conf
